Repository remerge/terraform-modules, pull requests merged in 2025-01, with the labels that each got.

#60 Add support for SW RAID, standard data partition and private network
  leaseweb/server/installation/main.tf
  leaseweb/server/installation/variables.tf
Labels: CORE

#63 Support Cloud SQL instance without site or cluster
  google/sql/postgresql/main.tf
  google/sql/postgresql/variables.tf
  netbox/vm/main.tf
  netbox/vm/variables.tf
Labels: AI

#62 Dsp 774 - define persistence config for google redis instance
  google/redis/main.tf
  google/redis/variables.tf
Labels: DSP

#64 DSP-774-fix-error-using-reserved-name-for-var
  google/redis/main.tf
  google/redis/variables.tf
Labels: DSP

#61 Use latest Terraform provider for Leaseweb
  leaseweb/server/installation/main.tf
  leaseweb/server/installation/versions.tf
  op/host/leaseweb/versions.tf
Labels: CORE
